[workspace]
members = ["xtask", "asteride", "pages", "elements", "config"]

default-members = ["asteride"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "2.0.0"
license = "Apache-2.0"
authors = [
  "playfairs <root@playfairs.cc>",
  "Invra <identificationsucks@gmail.com>",
]

[workspace.dependencies]
pico-args = "0.5.0"
tracing = "0.1.44"
image = "0.25.10"
toml = "1.1.2"
rfd = "0.17.2"

[workspace.dependencies.elements]
path = "./elements"

[workspace.dependencies.config]
path = "./config"

[workspace.dependencies.pages]
path = "./pages"

[workspace.dependencies.serde]
version = "1.0.228"
features = ["derive"]

[workspace.dependencies.lucide-icons]
version = "1.24.0"
features = ["iced"]

[workspace.dependencies.logging_subscriber]
git = "https://gitlab.com/invra/logging_subscriber"

[workspace.dependencies.tokio]
version = "1.52.3"
features = ["rt", "macros", "rt-multi-thread", "sync"]

[workspace.dependencies.iced]
version = "0.14.0"
features = ["image", "svg", "tokio"]
