[package]
name = "asteride"
description = "An IDE"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
iced.workspace = true
tokio.workspace = true
image.workspace = true
pages.workspace = true
config.workspace = true
tracing.workspace = true
elements.workspace = true
pico-args.workspace = true
lucide-icons.workspace = true
logging_subscriber.workspace = true
