# ------------------------------------------------------------------------ #
#  This file is part of AsterIDE.
# 
#  Copyright (c) 2026 playfairs
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      https://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ------------------------------------------------------------------------ #

[package]
name = "asteride"
edition = "2024"
version.workspace = true

[[bin]]
name = "asteride"
path = "src/main.rs"

[package.metadata.bundle]
name = "AsterIDE"
identifier = "dev.playfairs.asteride"
icon = [
  "../../assets/appIcon/icns/asteride-macOS-TintedLight-1024x1024@1x.icns",
]
version = "1.6.5"
resources = []
copyright = "Copyright (c) 2026"
category = "Developer"
short_description = "A Simple Text Editor written in Rust."
long_description = """
A Simple Text Editor written in Rust, made for Femboys 🌸.
"""

[dependencies]
command_palette = { path = "../command_palette" }
editor = { path = "../editor" }
search = { path = "../search" }
settings = { path = "../settings" }
tabs = { path = "../tabs" }
theme = { path = "../theme" }
plugins = { path = "../plugins" }

eframe = "0.34.1"
egui = "0.34.1"
rfd = "0.14"
walkdir = "2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
grep = "0.3"
grep-searcher = "0.1"
grep-regex = "0.1"
image = { version = "0.25", default-features = false, features = ["png"] }
